// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoanwvlidmsmiriiiwkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvYW53dmxpZG1zbWlyaWlpd2tsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjU1NDAsImV4cCI6MjA2NDk0MTU0MH0.B1nzb_uXZGk_KuhPLwPMQpSHp5j-xG8-7XY8Yb2xaCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);